name: pet_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.10
  google_sign_in: ^6.1.5
  provider: ^6.0.5
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  shared_preferences: ^2.2.1
  intl: ^0.18.1
  cached_network_image: ^3.3.1
  url_launcher: ^6.1.14
  flutter_local_notifications: ^16.1.0
  sqflite: ^2.3.0
  # Payment related
  flutter_stripe: ^10.0.0
  stripe_platform_interface: ^10.0.0
  # Firebase services
  firebase_auth: ^4.15.3
  cloud_functions: ^4.5.8