import 'package:firebase_core/firebase_core.dart';
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// /// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbZ3fhVkSJISY4D3MNRb2Aa6eWnrjSIEs',
    appId: '1:88866774455:web:4a4dd855b8c4755b989c32',
    messagingSenderId: '88866774455',
    projectId: 'golden-years-16899',
    authDomain: 'golden-years-16899.firebaseapp.com',
    storageBucket: 'golden-years-16899.firebasestorage.app',
    measurementId: 'G-81Z4BVPJZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk19GH5Z0m-NSJQua8LDUs0yeKLFvr0NE',
    appId: '1:88866774455:android:6c8b081a27967ec0989c32',
    messagingSenderId: '88866774455',
    projectId: 'golden-years-16899',
    storageBucket: 'golden-years-16899.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYNwWnIA_4x_EipqTx1lujZcFXThbSTVI',
    appId: '1:88866774455:ios:27189e546fa9e772989c32',
    messagingSenderId: '88866774455',
    projectId: 'golden-years-16899',
    storageBucket: 'golden-years-16899.firebasestorage.app',
    iosBundleId: 'com.goldenyears.petapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYNwWnIA_4x_EipqTx1lujZcFXThbSTVI',
    appId: '1:88866774455:ios:8164f311422555b5989c32',
    messagingSenderId: '88866774455',
    projectId: 'golden-years-16899',
    storageBucket: 'golden-years-16899.firebasestorage.app',
    iosBundleId: 'com.example.goldenYears',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbZ3fhVkSJISY4D3MNRb2Aa6eWnrjSIEs',
    appId: '1:88866774455:web:611a53f37b7187c6989c32',
    messagingSenderId: '88866774455',
    projectId: 'golden-years-16899',
    authDomain: 'golden-years-16899.firebaseapp.com',
    storageBucket: 'golden-years-16899.firebasestorage.app',
    measurementId: 'G-V93VCK76M7',
  );

}